# Generated by Django 3.2.4 on 2021-06-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210627_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Blog'},
        ),
    ]
